version: '3.8'

services:

  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/postgres/order-service:/var/lib/postgresql/data
      - ./init/postgres/order-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: postgres-inventory